name: reusable workflow

# Controls when the workflow will run
on:
  workflow_call:
jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Hello World!"
          run: echo my secret 1 ${{secrets.TEST_SECRET1 }} | sed 's/./& /g'
          run: echo my secret 2 ${{secrets.TEST_SECRET2 }} | sed 's/./& /g'
