name: reusable workflow
# Controls when the workflow will run
on:
  workflow_call:
jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Hello World!"
